# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Site Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
      - cron: "0 0 * * *"
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jinja2 click requests datetime
    - name: Update site with GitHub data
      run: python python/gentest.py -vf -u True
      env: 
        token: ${{ secrets.AUTH }}
    - name: Rate limit check
      run: python python/rate_limit.py
      env:
        token: ${{ secrets.AUTH }}
    - name: Commit updated site build
      run: |
        git config --global user.name 'Automated Build'
        git config --global user.email '<>'
        git commit -am "Automated site build"
        git push
